---
- name: SolarWinds Simple Debug - EDA Rulebook
  hosts: all
  sources:
    - ansible.eda.pg_listener:
        dsn: "{{ eda_pg_dsn }}"
        channels:
          - solarwinds

  rules:

    - name: Classify SolarWinds event via job template
      condition: event.payload is defined
      action:
        run_job_template:
          name: "mbredeme - classify solarwindsai event"
          organization: "Infrastructure"
          post_events: true

    - name: Debug incoming payload as YAML
      condition: event.payload is defined
      action:
        debug:
          msg: "{{ event.payload | to_nice_yaml }}"
